### ISSUE TITLE
No DHT sensor found

### ISSUE THREAD

**Issue by zafersn** [vilppuvuorinen/dht11-chip#1]
Hi everybody,
I am on the way to learning, how to write device driver, edit dts file, yocto etc. I wanted to incorporate my dht11 sensor into imx8 based dev board. 

firstly, I edited the dts file like below.

```
dht_sensors {
		compatible = "dht11";
		pinctrl-names = "default";
		pinctrl-0 = <&pinctrl_gpio_dht>;
		status = "okay";
		dht_room {

				label = "dht_room";
				gpios = <&gpio1 3 0>;

		};
	};
```
secondly,  I compiled dht11.c and got dht11.ko. then i inserted it into the kernel by running insmod dht11.ko.

finally, when I run probe-dht11 to get temp data, unfortunately, I get no dht11 sensors found error.

So I checked **/sys/bus/iio/devices** out. there is nothing in there. 

What should I do more, Do you have any suggestions?

Thank you

**Comment by vilppuvuorinen** [comment]
Sorry but I just barely remember what this thing was about.

On top of that I have not personally authored any of the stuff you seem to be interested in. I just got upset by the init hacks used by all the dht-11 tutorials I found and decided to deb package a version with systemd based auto loading.

Those C.H.I.P. dev boards were pretty sweet for the short period they were a thing tho.

**Comment by zafersn** [comment]
Thanks for your attention. I solved the problem by editing dts file like this below: 

```
dht11 {
		compatible = "dht11";
		pinctrl-names = "default";
		pinctrl-0 = <&pinctrl_gpio_dht>;
		gpios = <&gpio1 3 0>;
		status = "okay";
	};
```
